branch-protection-rules:
  - branch: main
    required_pull_request_reviews:
      required_approving_review_count: 1
    enforce_admins: true
    restrictions: null
    required_status_checks:
      strict: true
      contexts: []
    allow_force_pushes: false
    allow_deletions: false
